name: "docusaurus"
services:
  dev:
    container_name: dev-web
    build:
      context: .
      target: dev
    tty: true
    stdin_open: true
    profiles:
      - dev
    ports:
      - "3006:3006"
    volumes:
      - .:/opt/website
    environment:
      - NODE_ENV=development

  serve:
    container_name: serve-web
    build:
      context: .
      target: serve
    profiles:
      - prod
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production

  caddy:
    build:
      context: .
      target: caddy
    profiles:
      - caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DOCUSAURUS_DOMAIN=docusaurus.example
      - DOCUSAURUS_EMAIL=letsencrypt@docusaurus.example
    volumes:
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
