/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const homeItems = [
  {
    type: "doc",
    id: "note",
    label: "About taking notes",
  },
  {
    type: "category",
    label: "Psychology",
    className: "psychology",
    link: {
      type: "generated-index",
      slug: "Psychology?tags=psychology&operator=AND",
    },
    collapsed: true,
    items: [
      {
        type: "autogenerated",
        dirName: "Psychology",
      },
    ],
  },
  {
    type: "category",
    label: "Computer Science",
    className: "computer-science",
    link: {
      type: "generated-index",
      slug: "ComputerScience?tags=computer-science&operator=AND",
    },
    collapsed: true,
    items: [
      {
        type: "autogenerated",
        dirName: "ComputerScience",
      },
    ],
  },
  {
    type: "category",
    label: "Development Guide",
    className: "dev-guide",
    link: {
      type: "generated-index",
      slug: "Dev-Guide",
    },
    collapsed: true,
    items: [
      {
        type: "autogenerated",
        dirName: "Dev-Guide",
      },
    ],
  },
];

const csItems = [
  {
    type: "link",
    href: "/docs/note",
    label: "Back to Home",
  },
  {
    type: "link",
    href: "/docs/ComputerScience?tags=computer-science&operator=AND",
    label: "Search",
  },
  {
    type: "autogenerated",
    dirName: "ComputerScience",
  },
];

const psyItems = [
  {
    type: "link",
    href: "/docs/note",
    label: "Back to Home",
  },
  {
    type: "link",
    href: "/docs/Psychology?tags=psychology&operator=AND",
    label: "Search",
  },
  {
    type: "autogenerated",
    dirName: "Psychology",
  },
];

const devguideItems = [
  {
    type: "link",
    href: "/docs/note",
    label: "Back to Home",
  },
  {
    type: "autogenerated",
    dirName: "Dev-Guide",
  },
];

const sidebars = {
  homeSidebar: homeItems,
  csSidebar: csItems,
  psySidebar: psyItems,
  devGuideSidebar: devguideItems,
};

module.exports = sidebars;
