name: Pull request build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "LICENSE"
    branches:
      - "main"

jobs:
  build:
    name: Lint and build website
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build website
        run: npm run build

  markdown-check:
    name: Check Markdown documents
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run LanguageTool
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          patterns: "**.md"
          # LanguageTool flags - see https://languagetool.org/http-api/swagger-ui/#!/default/post_check
          language: "en-US"
          enabled_rules: "WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE"
          disabled_categories: "TYPOS,TYPOGRAPHY,CASING"

      - name: Run misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "**.md"
          level: info
          locale: "US"

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          file-extension: ".md"
          check-modified-files-only: "yes"
          config-file: ".mlc.config.json"
          folder-path: "blog, src/components/talks/abstracts, src/components/homepage"
          base-branch: "main"
